id: P62EB5D10
initial_creation_type: ocr
source_metadata:
  volumes:
    d05e6220d61f4b91b2b65b3ba15cc18c:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: བདག་མེད་མ་ལྷ་མོ་བཅོ་ལྔ་ལ་བསྟོད་པ།
      total_pages: 1712
      volume_number: 42
